version: '3.7'
name: driving_school
services:
  postgresdb:
    image: postgres:latest
    hostname: postgresql
    container_name: postgres-container-app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=driving_school
    networks:
      - net.driving_school.sh

#  sonarqube:
#    image: sonarqube
#    container_name: sonarqube-container
#    ports:
#      - 9000:9000
#    networks:
#      - net.driving_school.sh

networks:
  net.driving_school.sh:
    name: net.driving_school.sh
    driver: bridge
